// <auto-generated />
namespace QuoteSystem.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtechuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtechuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201504071526011_addtechuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
